routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => false]);

Route::group(['middleware' => ['auth'], 'as' => 'admin.'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('users', UserController::class);
    Route::resource('clients', ClientController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('tasks', TaskController::class);
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'contact_name',
        'contact_email',
        'contact_phone_number',
        'company_name',
        'company_address',
        'company_phone_number',
    ];

    public function projects()
    {
        return $this->hasMany(Project::class);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreClientRequest;
use App\Http\Requests\UpdateClientRequest;
use App\Models\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();

        return view('admin.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreClientRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreClientRequest $request)
    {
        Client::create($request->validated());

        return redirect()->route('admin.clients.index')->with('success', 'Cliente creado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('admin.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateClientRequest  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateClientRequest $request, Client $client)
    {
        $client->update($request->validated());

        return redirect()->route('admin.clients.index')->with('success', 'Cliente editado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();

        return back();
    }
}

resources/views/admin/clients/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Nuevo Cliente</h1>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <form method="POST" action="{{route('admin.clients.store')}}">
                            @csrf
                            <div class="form-group">
                                <label for="contact_name" class="required">Nombre del cliente </label>
                                <input type="text" name="contact_name" id="contact_name" class="form-control {{$errors->has('contact_name') ? 'is-invalid' : ''}}" placeholder="Ingrese el nombre del cliente" value="{{old('contact_name', '')}}">
                                @if ($errors->has('contact_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="contact_email" class="required">Email del cliente </label>
                                <input type="email" name="contact_email" id="contact_email" class="form-control {{$errors->has('contact_email') ? 'is-invalid' : ''}}" placeholder="Ingrese el email del cliente" value="{{old('contact_email', '')}}">
                                @if ($errors->has('contact_email'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_email') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="contact_phone_number" class="required">Teléfono del cliente</label>
                                <input type="text" name="contact_phone_number" id="contact_phone_number" class="form-control {{$errors->has('contact_phone_number') ? 'is-invalid' : ''}}" placeholder="Ingrese el teléfono del cliente" value="{{old('contact_phone_number', '')}}">
                                @if ($errors->has('contact_phone_number'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_phone_number') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_name" class="required">Nombre de la empresa</label>
                                <input type="text" name="company_name" id="company_name" class="form-control {{$errors->has('company_name') ? 'is-invalid' : ''}}" placeholder="Ingrese el nombre de la empresa" value="{{old('company_name', '')}}">
                                @if ($errors->has('company_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_address" class="required">Dirección de la empresa</label>
                                <input type="text" name="company_address" id="company_address" class="form-control {{$errors->has('company_address') ? 'is-invalid' : ''}}" placeholder="Ingrese la dirección de la empresa" value="{{old('company_address', '')}}">
                                @if ($errors->has('company_address'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_address') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_phone_number" class="required">Teléfono de la empresa</label>
                                <input type="text" name="company_phone_number" id="company_phone_number" class="form-control {{$errors->has('company_phone_number') ? 'is-invalid' : ''}}" placeholder="Ingrese el teléfono de la empresa" value="{{old('company_phone_number', '')}}">
                                @if ($errors->has('company_phone_number'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_phone_number') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="row d-print-none mt-2">
                                <div class="col-12 text-right">
                                    <a class="btn btn-danger" href="{{route('admin.clients.index')}}">
                                        <i class="fa fa-fw fa-lg fa-arrow-left"></i>
                                        Regresar
                                    </a>
                                    <button class="btn btn-success" type="submit">
                                        <i class="fa fa-fw fa-lg fa-check-circle"></i>Guardar
                                    </button>
                                </div>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Editar Cliente</h1>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="{{route('admin.clients.update', $client->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="contact_name" class="required">Nombre del cliente </label>
                                <input type="text" name="contact_name" id="contact_name" class="form-control {{$errors->has('contact_name') ? 'is-invalid' : ''}}" placeholder="Ingrese el nombre del cliente" value="{{old('contact_name', $client->contact_name)}}">
                                @if ($errors->has('contact_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="contact_email" class="required">Email del cliente </label>
                                <input type="email" name="contact_email" id="contact_email" class="form-control {{$errors->has('contact_email') ? 'is-invalid' : ''}}" placeholder="Ingrese el email del cliente" value="{{old('contact_email', $client->contact_email)}}">
                                @if ($errors->has('contact_email'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_email') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="contact_phone_number" class="required">Teléfono del cliente</label>
                                <input type="text" name="contact_phone_number" id="contact_phone_number" class="form-control {{$errors->has('contact_phone_number') ? 'is-invalid' : ''}}" placeholder="Ingrese el teléfono del cliente" value="{{old('contact_phone_number', $client->contact_phone_number)}}">
                                @if ($errors->has('contact_phone_number'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('contact_phone_number') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_name" class="required">Nombre de la empresa</label>
                                <input type="text" name="company_name" id="company_name" class="form-control {{$errors->has('company_name') ? 'is-invalid' : ''}}" placeholder="Ingrese el nombre de la empresa" value="{{old('company_name', $client->company_name)}}">
                                @if ($errors->has('company_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_name') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_address" class="required">Dirección de la empresa</label>
                                <input type="text" name="company_address" id="company_address" class="form-control {{$errors->has('company_address') ? 'is-invalid' : ''}}" placeholder="Ingrese la dirección de la empresa" value="{{old('company_address', $client->company_address)}}">
                                @if ($errors->has('company_address'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_address') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="company_phone_number" class="required">Teléfono de la empresa</label>
                                <input type="text" name="company_phone_number" id="company_phone_number" class="form-control {{$errors->has('company_phone_number') ? 'is-invalid' : ''}}" placeholder="Ingrese el teléfono de la empresa" value="{{old('company_phone_number', $client->company_phone_number)}}">
                                @if ($errors->has('company_phone_number'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_phone_number') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="row d-print-none mt-2">
                                <div class="col-12 text-right">
                                    <a class="btn btn-danger" href="{{route('admin.clients.index')}}">
                                        <i class="fa fa-fw fa-lg fa-arrow-left"></i>
                                        Regresar
                                    </a>
                                    <button class="btn btn-success" type="submit">
                                        <i class="fa fa-fw fa-lg fa-check-circle"></i>Editar
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Listado de Clientes</h1>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container-fluid">

        @if (session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <a href="{{ route('admin.clients.create') }}" class="btn btn-primary mb-3">Nuevo Cliente</a>

                        <table class="table table-bordered" id="client_table">
                            <thead>
                                <tr>
                                    <th>Nombre del cliente</th>
                                    <th>Email del cliente</th>
                                    <th>Telefono del cliente</th>
                                    <th>Nombre de la Empresa</th>
                                    <th>Direccion de la Empresa</th>
                                    <th>Telefono de la empresa</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($clients as $client)
                                <tr>
                                    <td>{{$client->contact_name}}</td>
                                    <td>{{$client->contact_email}}</td>
                                    <td>{{$client->contact_phone_number}}</td>
                                    <td>{{$client->company_name}}</td>
                                    <td>{{$client->company_address}}</td>
                                    <td>{{$client->company_phone_number}}</td>
                                    <td>
                                        <a href="{{ route('admin.clients.edit', $client->id) }}" class="btn btn-success">
                                            Editar
                                        </a>

                                        <form action="{{ route('admin.clients.destroy', $client->id) }}" id="delete_form" method="POST" onsubmit="return confirm('Esta seguro que desea eliminar el registro?')" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-danger" value="Eliminar">
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        $('#client_table').DataTable();
    });
</script>
@endsection